### ISSUE TITLE
Profile picture implemented into database

### ISSUE THREAD

**Issue by brandenHusted** [calvin-cs262-fall2023-teamA/client#112]
This could be a lot of storage space although your profile picture is not stored in the database. Do we want to do this because it may not be necessary.

**Comment by StevenM-Calvin** [comment]
I'm working on this. The images are currently uploaded to the storage account, but not downloaded on the client. In other words, when you set a new profile pick, it's getting saved but it isn't being used yet. I'm hoping to have this implemented by tonight.

**Comment by StevenM-Calvin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Store Profile Images in Storage Account](https://trello.com/c/bbXjHoWD/201-store-profile-images-in-storage-account)

**Comment by StevenM-Calvin** [comment]
Resolved by a merged branch
