### ISSUE TITLE
Detail Page Flex Styling Bug

### ISSUE THREAD

**Issue by StevenM-Calvin** [calvin-cs262-fall2023-teamA/client#92]
Description/name/email is cut off at the edge of the screen on my (Steven’s) phone.

See image on Trello card for details.

**Comment by StevenM-Calvin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Detail Page Flex Styling Bug](https://trello.com/c/Xx2hVFQG/208-detail-page-flex-styling-bug)

**Comment by harryg02** [comment]
#96
